apiVersion: v1
kind: Service
metadata:
  name: svc-pgsql
  labels:
    name: svc-pgsql
spec:
  ports:
    # the port that this service should serve on
    - name: tcp
      port: 5432
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: pgsql
