apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: reg.17mei.top/redis/redis:latest
          ports:
          - containerPort: 6347
            name: tcp
          env:
            - name: REDIS_PASS
              value: meidb

