apiVersion: v1
kind: ReplicationController
metadata: 
 name: story
spec: 
 replicas: 1
 selector: 
  app: story
 template: 
  metadata: 
   labels: 
    app: story
  spec: 
   containers: 
    - 
   name: story
     image: "reg.17mei.top/story/cdc7233f-story:v1.2"
     imagePullPolicy: Always
     ports: 
      - 
   containerPort: 3000
       name: tcp
     env: 
      - 
   name: CH
       value: {{SVC_CONSUL_SERVICE_HOST}}
      - 
   name: CP
       value: {{SVC_CONSUL_SERVICE_PORT_CONSULDNS}}
      - 
   name: SS
       value: ".service.dc1.consul"
      - 
   name: DH
       value: {{SVC_PGSQL_SERVICE_HOST}}
      - 
   name: DN
       value: meidb
      - 
   name: DP
       value: 5432
      - 
   name: DPWD
       value: wothing
      - 
   name: DU
       value: postgres
      - 
   name: P
       value: 3000
